seed: 1234
lr: 1e-04
grad_accum: 1
grad_ckpt: True
gpu: 1
fp16: False
n_hidden: 16
emb_dim: 32
nargs_ratio: [0.2, 0.4, 0.6, 0.8] # ratio of exposed atomic events to model for next step prediction 
num_epochs: 100
batch_size: 4
every_n_epochs: 50 
debug: False
early_stopping: False
checkpointing: True
queue: compute
remote: False
dataset: LDC
trained_model_path: 
train: True
test: True


